name: CI
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run tests
        run: go test ./...
      - name: Run coverage (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: go test -coverprofile=coverage.out ./...
      - name: Show coverage summary (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: go tool cover -func=coverage.out | grep total || true
      - name: Enforce fetcher coverage threshold (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          FETCHER_LINE=$(go tool cover -func=coverage.out | awk '/github.com\/wosiu6\/docky-go\/internal\/fetcher$/')
          if [ -z "$FETCHER_LINE" ]; then echo "Fetcher line not found"; exit 2; fi
          PCT=$(echo "$FETCHER_LINE" | awk '{print $3}' | tr -d '%')
          awk -v pct="$PCT" 'BEGIN { if (pct+0 < 80.0) { printf "Fetcher coverage %.1f%% below threshold\n", pct; exit 1 } else { printf "Fetcher coverage %.1f%% OK\n", pct } }'
      - name: Upload coverage artifact (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
